# Generated by Django 2.0.3 on 2018-04-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amw', '0003_serverinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='tmdbid',
            field=models.CharField(default='', max_length=20),
        ),
    ]
