# Generated by Django 2.0.3 on 2018-04-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amw', '0004_tvshow_tmdbid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='tmdbid',
            new_name='imdbid',
        ),
    ]
