# Generated by Django 2.0.3 on 2018-04-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amw', '0005_auto_20180402_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='imdbid',
            new_name='tvdbid',
        ),
    ]
