# Generated by Django 2.0.3 on 2018-04-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amw', '0006_auto_20180402_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='bannerurl',
            field=models.CharField(default='', max_length=20),
        ),
    ]
