# Generated by Django 2.2.4 on 2019-08-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amw', '0009_auto_20190810_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='bannerurl',
            new_name='banner_url',
        ),
        migrations.AddField(
            model_name='plexmediaserver',
            name='tv_shows',
            field=models.ManyToManyField(blank=True, related_name='associated_servers', to='amw.TVShow'),
        ),
    ]
