# Generated by Django 2.2.4 on 2019-08-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amw', '0010_auto_20190810_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='plexuser',
            name='authenticationToken',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plexmediaserver',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='tvdbid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
