# Generated by Django 2.2.4 on 2019-08-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amw', '0011_auto_20190810_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='tvdbid',
            field=models.IntegerField(unique=True),
        ),
    ]
